### ISSUE TITLE
Build updated code

### ISSUE THREAD

**Issue by AmirBitaraf** [RotatingFans/i915ovmfPkg#2]
Hi @RotatingFans,
First of all thanks for your awesome contribution. I wanted to build the rom in order to test and help If I can.
The first problem I faced was that the default environment mentioned in docs threw lots of errors (It considered warnings as errors) and I fixed it by removing `-Werror` from compiler flags in `Conf`.
Next, there is typo in documentation that mentions cloning of EDKII-Packages which does not exist. By reading build codes I managed to clone `edk2-platforms`.
After fixing these, the current problem is that `PIPE_DATA_M1` and other variables are undefined in linker. As I made some search, they are found in i915 module. So I'll appreciate if you can help solving this problem and tell me what should I link.

Here are the errors:
```
lld-link: error: undefined symbol: PIPE_DATA_M1                            
>>> referenced by WORKSPACE/i915ovmfPkg/i915_dp.c                
>>>               i915ovmf.lib(i915_dp.obj)                                
                                                                           
lld-link: error: undefined symbol: PIPE_DATA_N1      
>>> referenced by WORKSPACE/i915ovmfPkg/i915_dp.c                
>>>               i915ovmf.lib(i915_dp.obj)                                
                                                                           
lld-link: error: undefined symbol: PIPE_LINK_M1                            
>>> referenced by WORKSPACE/i915ovmfPkg/i915_dp.c                                                                                           
>>>               i915ovmf.lib(i915_dp.obj)                                
                                                                           
lld-link: error: undefined symbol: PIPE_LINK_N1     
>>> referenced by WORKSPACE/i915ovmfPkg/i915_dp.c
>>>               i915ovmf.lib(i915_dp.obj)    
```
Here's my environment:

**OS**: Linux 5.7.15-200.fc32.x86_64 (Fedora 32 Workstation Edition)
**iGPU**: Intel Corporation UHD Graphics 620 [8086:5917] (rev 07)
**Compilers**:
- clang version 10.0.0 (Fedora 10.0.0-2.fc32)
- gcc (GCC) 10.2.1 20200723 (Red Hat 10.2.1-1)

**Comment by RotatingFans** [comment]
Thank you for attempting to try it out! I just pushed a fix for the issue. You may have to clean the project by deleting the build folder(you can use the included clean.sh script). I also fixed the documentation and plan to work on cleaning up the errors.

**Comment by RotatingFans** [comment]
That's great. Most of my work has been with GVT-D, so most of the issues / steps you mentioned would be great to be documented in the readme. I will compile the steps together so that its much clearer to use.

**Comment by RotatingFans** [comment]
I have compiled a lot of the steps and rewritten sections of code & Scripts to make it work better. Let me know if there are any issues still.
